[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "tmux rename-window \"dofiles\"; tmux new-window -dn nvim \"cd .config/nvim; nvim .\"; nvim ."

[[session]]
name = "fema"
path = "~/dev/work/krbl/fema"
startup_command = "tmux rename-window \"server\"; tmux new-window -dn client \"cd FemaServer/tests/deviceGateway/client; nvim .\"; tmux new-window -dn tests \"cd FemaTests; nvim .\"; cd FemaServer; nvim ."

[[session]]
name = "go-refs"
path = "~/dev/third_party/go-references"

[[session]]
name = "misc"
path = "~"

[[session]]
name = "polygon"
startup_command = "ssh polygon"

[[session]]
name = "daily"
path = "~/daily"
startup_command = "daily; nvim ."

[[session]]
name = "tmp"
startup_command = "tmux rename-session \"tmp$(sesh list -t | grep 'tmp\\d' | wc -l | xargs)\"; clear"

[[session]]
name = "new"
startup_command = "tmux command-prompt -p 'New session name:' \"rename-session '%%'\"; clear"
